//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int Id { get; set; }
        public int Seller { get; set; }
        public string Region { get; set; }
        public string Suburb { get; set; }
        public string Location { get; set; }
        public Nullable<int> Room { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> FloorArea { get; set; }
        public Nullable<decimal> LandArea { get; set; }
        public Nullable<decimal> RV { get; set; }
        public string Email { get; set; }
    
        public virtual Seller Seller1 { get; set; }
    }
}
