//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int HouseId { get; set; }
        public int SellerId { get; set; }
        public string Region { get; set; }
        public string Suburb { get; set; }
        public string Location { get; set; }
        public int Room { get; set; }
        public string Type { get; set; }
        public decimal FloorArea { get; set; }
        public decimal LandArea { get; set; }
        public decimal RV { get; set; }
        public string Email { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
